// <auto-generated />
namespace QBO_Events_Management.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Status : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Status));
        
        string IMigrationMetadata.Id
        {
            get { return "201706131120115_Status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
