// <auto-generated />
namespace QBO_Events_Management.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Renche21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Renche21));
        
        string IMigrationMetadata.Id
        {
            get { return "201707180434093_Renche21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
